#!/bin/sh

# set -e
case $1 in
   start)
     (
     flock -n 9 || exit 1
     touch /var/run/nodedone_pid
     tail -F /var/log/messages | awk '/wwlogger/ && /vnfs/ && /stateful/ {system("/bin/wwsh -y provision set --bootlocal=exit " $4)}' &> /var/log/nodedone &
     jobs -p > /var/run/nodedone_pid
     ) 9>/var/lock/nodedone
     ;;
   stop)
     kill  $(</var/run/nodedone_pid)
     rm -f /var/run/nodedone_pid
     rm -f /var/lock/nodedone
     ;;
   *)
     echo "Usage: $0 {start|stop}"
     exit 2
     ;;
esac
