#!/bin/bash

# set -e
case $1 in
   start)
     (
     flock -n 9 || exit 1
     touch /var/run/nodedone_pid
     (tail -f /var/log/messages & echo $! >&3 ) 3>/var/run/nodedone_pid | \
     awk '/wwlogger/ && /vnfs/ && /stateful/ {system("/bin/wwsh -y provision set --bootlocal=exit " $4)}' &> /var/log/nodedone &

     echo $(</var/run/nodedone_pid)

     ) 9>/var/lock/nodedone
     ;;
   stop)
     kill  $(</var/run/nodedone_pid)
     rm -f /var/run/nodedone_pid
     rm -f /var/lock/nodedone
     ;;
   *)
     echo "Usage: $0 {start|stop}"
     exit 2
     ;;
esac
