#!/bin/bash

## reimage vnfs
wwvnfs -y --chroot /var/chroots/centos-6-stateful

## reboot all compute nodes
echo rebooting all compute nodes ...
sleep 3
pdsh -w `grep eth0 /etc/hosts | awk '{print $1}' | paste -d, -s ` reboot
